#+TITLE: Consultas SQL
#+SETUPFILE: ../../template.org
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../css/index.css" />
1. Titulo de las peliculas producidas despues del año 2005
   #+begin_src sql
   SELECT titulo
   FROM   peliculas
   WHERE  anno > 2005
   #+end_src

2. Precio y formato de las peliculas de menos de 1 euro
   #+begin_src sql
   SELECT precio, formato
   FROM   peliculas
   WHERE  precio < 1
   #+end_src

3. Titulo de las peliculas en formato DVD
   #+begin_src sql
   SELECT titulo
   FROM   peliculas
   WHERE  formato = 'DVD'
   #+end_src

4. Listado con los formetos de las peliculas
   #+begin_src sql
   SELECT DISTINCT formato
   FROM   peliculas
   #+end_src

5. Cuantas peliculas se produjeron en los 3 ultimos años
   #+begin_src sql
   SELECT COUNT(*)
   FROM   peliculas
   WHERE  anno >= 2019
   #+end_src

6. Cuantos DVDs estan de oferta
   #+begin_src sql
   SELECT COUNT(*)
   FROM   peliculas
   WHERE  oferta = 'S' AND formato = 'DVD'
   #+end_src

7. Precio mas caro de una pelicula
   #+begin_src sql
   SELECT MAX(precio)
   FROM   peliculas
   #+end_src

8. Año de la pelicula mas antigua
   #+begin_src sql
   SELECT MIN(anno)
   FROM   peliculas
   #+end_src

9. Cuantas peliculas no estan en MP4
   #+begin_src sql
   SELECT COUNT(*)
   FROM   peliculas
   WHERE  formato != 'MP4'
   #+end_src

10. Titulo de las peliculas que empiezan por 'M'
    #+begin_src sql
    SELECT titulo
    FROM   peliculas
    WHERE  titulo LIKE 'M%'
    #+end_src

11. Cuantos titulos de peliculas estan formados por mas de una palabra
    #+begin_src sql
    SELECT titulo
    FROM   peliculas
    WHERE  titulo LIKE '% %'
    #+end_src

12. Cuantas peliculas se han alquilado en Febrero
    #+begin_src sql
    SELECT COUNT(*)
    FROM   alquiler
    WHERE  FECHA LIKE '__/02/%'
    #+end_src

13. Codigo de los socios que no han devuelto las pelis que alquilaron
    #+begin_src sql
    SELECT c_socio
    FROM   alquiler
    WHERE  devuelta = 'N'
    #+end_src

14. Nombre de los socios que presublimenete son chicas
    #+begin_src sql
    SELECT nombre
    FROM   alquiler
    WHERE  nombre LIKE '%a'
    #+end_src

15. Que titulos de peliculas no estan ni en DVD ni en MP4
    #+begin_src sql
    SELECT titulo
    FROM   peliculas
    WHERE  formato != 'DVD'
      AND  formato != 'MP4'
    #+end_src

16. Cuantas peliculas hay de matrix
    #+begin_src sql
    SELECT COUNT(*)
    FROM   peliculas
    WHERE  titulo LIKE 'Matrix%'
    #+end_src

17. Cuantas peliculas se alquilaron en febrero de 2002
    #+begin_src sql
    SELECT COUNT(*)
    FROM   alquiler
    WHERE  fecha LIKE '__/02/02'
    #+end_src

18. Nombre de nuestros socios que presumiblemente son chicas
    #+begin_src sql
    SELECT nombre
    FROM   socios
    WHERE  nombre LIKE '%a'
    #+end_src

19. Código de los socios que en el 2005 no nos devolvieron las
    peliculas alquiladas
    #+begin_src sql
    SELECT c_socio
    FROM   alquiler
    WHERE  fecha LIKE '__/__/05'
      AND  devuelta = 'N'
    #+end_src

20. Precio de la película mas cara
    #+begin_src sql
    SELECT MAX(precio)
    FROM   peliculas
    #+end_src

21. Nombre de paises que tienen menos de 7 letras
    #+begin_src sql
    SELECT nombre_pais
    FROM   paises
    WHERE  LENGTH(nombre_pais) < 7
    #+end_src

22. Visualiza los distintos formatos de las películas
    #+begin_src sql
    SELECT DISTINCT formato
    FROM   peliculas
    #+end_src

23. Título de las pelis que valen 2 euros o 2 euros y pico
    #+begin_src sql
    SELECT titulo
    FROM   peliculas
    WHERE  precio >= 2
      AND  precio < 3
    #+end_src

24. En qué año se produjo la primera película
    #+begin_src sql
    SELECT MIN(anno)
    FROM   peliculas
    #+end_src

25. Título de las películas que se han producido en los últimos 10
    años
    #+begin_src sql
    SELECT titulo
    FROM   peliculas
    WHERE  anno > TO_CHAR(
             ADD_MONTHS(SYSDATE, -12*10),
             'YYYY'
           )
    #+end_src

26. Precio medio de los dvds
    #+begin_src sql
    SELECT AVG(precio)
    FROM   peliculas
    #+end_src

27. Cuato valen todos los DVDs que tenemos
    #+begin_src sql
    SELECT SUM(precio)
    FROM   peliculas
    #+end_src

28. Cuantos cines existen entre España, Francia y Portugal
    #+begin_src sql
    SELECT SUM(cines)
    FROM   paises
    WHERE  nombre_pais in ( 'España', 'Francia', 'Portugal' )
    #+end_src

29. Cuanto valen todas las peliculas que no están ni en BR ni en MP4
    #+begin_src sql
    SELECT SUM(precio)
    FROM   peliculas
    WHERE  NOT formato = 'BR'
      AND  NOT formato = 'MP4'
    #+end_src

30. Precio mas caro de una pelicula en oferta
    #+begin_src sql
    SELECT MAX(precio)
    FROM   peliculas
    WHERE  oferta = 'S'
    #+end_src

31. Cuantos socios son de Toledo
    #+begin_src sql
    SELECT COUNT(*)
    FROM   socios
    WHERE  telefono LIKE '925%'
    #+end_src

32. Cual es la facturación total del 2º semestre de 2002
    #+begin_src sql
    SELECT SUM(precio)
    FROM   peliculas, alquiler
    WHERE  SUBSTR(fecha, 4, 2) > 6
      AND  fecha LIKE '__/__/02'
    #+end_src

33. Que codigos de socio alquilan películas en Enero
    #+begin_src sql
    SELECT c_socio
    FROM   alquiler
    WHERE  fecha LIKE '__/01/__'
    #+end_src

34. Cuanto dinero se ha gastado el socio de código 1001
    #+begin_src sql
    SELECT SUM(precio)
    FROM   alquiler, peliculas
    WHERE  c_socio = 1001
    #+end_src

35. Visualizar los paises de más de 8000 cines ordenados
    alfabeticamente
    #+begin_src sql
    SELECT   nombre_pais
    FROM     paises
    WHERE    cines > 8000
    ORDER BY nombre_pais
    #+end_src

36. Cuantas veces se ha alquilado la pelicula de codigo 2
    #+begin_src sql
    SELECT COUNT(*)
    FROM   alquiler
    WHERE  c_peli = 2
    #+end_src

37. Nombre de los hermanos de Gema Ramirez Lopez
    #+begin_src sql
    SELECT nombre
    FROM   socios
    WHERE  ape1 = 'ramirez'
      AND  ape2 = 'lopez'
      AND  NOT nombre = 'gema'
    #+end_src

38. Despues del 2000 en cuantos años no se han producido peliculas
    #+begin_src sql
    SELECT SUBSTR(SYSDATE, 7, 2)
           - COUNT(DISTINCT anno)
    FROM   peliculas
    WHERE  anno > 2000
    #+end_src

39. Visualiza en que años se han alquilado peliculas
    #+begin_src sql
    SELECT DISTINCT SUBSTR(fecha, 7, 2)
    FROM   alquiler
    #+end_src

40. Cuantas peliculas hay de Tiburon
    #+begin_src sql
    SELECT COUNT(*)
    FROM   peliculas
    WHERE  titulo LIKE 'Tiburón%'
    #+end_src

41. Cuantos alquileres de un solo dia no se han devuelto
    #+begin_src sql
    SELECT COUNT(*)
    FROM   alquiler
    WHERE  ndias = 1
      AND  devuelta = 'N'
    #+end_src

42. Cuantos socios viven en la calle oro
    #+begin_src sql
    SELECT COUNT(*)
    FROM   socios
    WHERE  direccion LIKE 'oro,%'
    #+end_src

43. Que titulo de peliculas es la mas cara
    #+begin_src sql
    SELECT titulo
    FROM   peliculas
    WHERE  precio = (SELECT MAX(precio) FROM peliculas)
    #+end_src

44. Cual es el titulo de la pelicula mas moderna
    #+begin_src sql
    SELECT titulo
    FROM   peliculas
    WHERE  anno = (SELECT MAX(anno) FROM PELICULAS)
    #+end_src

45. En que formato esta la pelicula mas barata
    #+begin_src sql
    SELECT DISTINCT formato
    FROM   peliculas
    WHERE  precio = (SELECT MIN(precio) FROM PELICULAS)
    #+end_src

46. Cuando se hizo el ultimo alquiler
    #+begin_src sql
    SELECT MAX(fecha)
    FROM   alquiler
    #+end_src

47. Cual es el pais que tiene mas cines
    #+begin_src sql
    SELECT nombre_pais
    FROM   paises
    WHERE  cines = (SELECT MAX(cines) FROM paises)
    #+end_src

48. Titulo de las peliculas españolas
    #+begin_src sql
    SELECT titulo
    FROM   peliculas
    WHERE  c_pais = (
             SELECT c_pais
             FROM   paises
             WHERE  nombre_pais = 'España'
           )
    #+end_src

49. Titulo de las peliculas que no se alquilan
    #+begin_src sql
    SELECT titulo
    FROM   peliculas
    WHERE  c_peli NOT IN (
             SELECT DISTINCT c_peli
             FROM alquiler
           )
    #+end_src

50. Nombre de los hermanos de Laura.
    #+begin_src sql
    SELECT nombre
    FROM   socios
    WHERE  ape1 = (
             SELECT ape1
             FROM   socios
             WHERE  nombre = 'laura'
           )
      AND  ape2 = (
             SELECT ape2
             FROM   socios
             WHERE  nombre = 'laura'
           )
      AND  nombre != 'laura'
    #+end_src

51. Titulo de las peliculas del pais que menos cines tiene
    #+begin_src sql
    SELECT titulo
    FROM   peliculas
    WHERE  c_pais = (
             SELECT c_pais
             FROM   paises
             WHERE  cines = (
               SELECT MIN(cines)
               FROM   paises
             )
           )
    #+end_src

52. Codigo de la peliculas que se alquilo la primera vez
    #+begin_src sql
    SELECT c_peli
    FROM   alquiler
    WHERE  fecha = (
             SELECT MIN(fecha)
             FROM   alquiler
           )
    #+end_src

53. Codigo del socio que realizo el alquiler mas barato
    #+begin_src sql
    SELECT c_socio
    FROM   alquiler
    WHERE  total = (
             SELECT MIN(total)
             FROM   alquiler
           )
    #+end_src

54. Cuantas peliculas tenemos en los diferentes formatos
    #+begin_src sql
    SELECT   COUNT(formato), formato
    FROM     peliculas
    GROUP BY formato
    #+end_src

55. Listado con el numero de alquileres realizados los diferentes años
    #+begin_src sql
    SELECT   substr(fecha, 7, 2), COUNT(*)
    FROM     alquiler
    GROUP BY substr(fecha, 7, 2)
    ORDER BY substr(fecha, 7, 2)
    #+end_src

56. Listado de los precios de las peliculas mas caras en los
    diferentes años
    #+begin_src sql
    SELECT   anno, MAX(precio)
    FROM     peliculas
    GROUP BY anno
    ORDER BY anno
    #+end_src

57. Listado con el total que hemos facturada los distintos años,
    alquilando peliculas
    #+begin_src sql
    SELECT   substr(fecha, 7, 2), SUM(total)
    FROM     alquiler
    GROUP BY substr(fecha, 7, 2)
    ORDER BY substr(fecha, 7, 2)
    #+end_src

58. Cuantos DVDs españoles hay?
    #+begin_src sql
    SELECT COUNT(*)
    FROM   peliculas
    WHERE  formato = 'DVD'
      and  c_pais = (
             SELECT c_pais
             FROM   paises
             WHERE  nombre_pais = 'España'
          )
    #+end_src

59. Listado con las diferencias familias socias (1er apellido) junto
    con el numero de integrantes que tiene cada familia.
    #+begin_src sql
    SELECT   ape1, COUNT(*)
    FROM     socios
    GROUP BY ape1
    ORDER BY ape1
    #+end_src

60. Listado con los diferentes titulos de peliculas que se han ido
    produciendo los diferentes años.
    #+begin_src sql
    SELECT   anno, titulo
    FROM     peliculas
    ORDER BY anno, titulo
    #+end_src

61. Listado con el titulo de las peliculas junto con el nombre de pais
    al que pertenece.
    #+begin_src sql
    SELECT   pe.titulo, pa.nombre_pais
    FROM     peliculas pe, paises pa
    WHERE    pe.c_pais = pa.c_pais
    ORDER BY pe.titulo
    #+end_src

62. Listado con los titulos de las peliculas que se han alquildado
    junto con la fecha en que se alquilo
    #+begin_src sql
    SELECT   a.fecha, p.titulo
    FROM     peliculas p, alquiler a
    WHERE    p.c_peli = a.c_peli
    ORDER BY a.fecha
    #+end_src

63. Nombre de los socios que no han visto ninguna de Torrente.
    #+begin_src sql
    SELECT   nombre, ape1
    FROM     socios
    WHERE    c_socio NOT IN (
               SELECT c_socio
               FROM   alquiler
               WHERE  c_peli IN (
                        SELECT c_peli
                        FROM   peliculas
                        WHERE  titulo LIKE 'Torrente%'
                      )
             )
    ORDER BY nombre
    #+end_src

64. Nombre de los socios que alquilaron el año pasado.
    #+begin_src sql
    SELECT   s.nombre, s.ape1
    FROM     socios s, alquiler a
    WHERE    s.c_socio = a.c_socio
      AND    SUBSTR(a.fecha, 7, 2) = SUBSTR(SYSDATE, 7, 2) - 1
    ORDER BY a.nombre
    #+end_src

65. Nombre de los paises que no alquilan sus peliculas.
    #+begin_src sql
    SELECT   nombre_pais
    FROM     paises
    WHERE    c_pais NOT IN (
               SELECT c_pais
               FROM   peliculas
               WHERE  c_peli IN (
                        SELECT c_peli
                        FROM   alquiler
                      )
             )
    ORDER BY nombre_pais
    #+end_src

66. Nombre y apellidos de los socios que alquilan peliculas españolas.
    #+begin_src sql
    SELECT nombre, ape1
    FROM   socios
    WHERE  c_socio IN (
             SELECT c_socio
             FROM   alquiler
             WHERE  c_peli IN (
                      SELECT c_peli
                      FROM   peliculas
                      WHERE  c_pais = (
                               SELECT c_pais
                               FROM   paises
                               WHERE  nombre_pais = 'España'
                             )
                    )
           )
    ORDER BY nombre
    #+end_src

67. Cuantos socios han alquilado algun DVD?
    #+begin_src sql
    SELECT COUNT(DISTINCT c_socio)
    FROM   alquiler
    WHERE  c_peli IN (
             SELECT c_peli
             FROM   peliculas
             WHERE  formato = 'DVD'
           )
   #+end_src

68. Cuantos paises tienen mas cines que la media de los paises?
    #+begin_src sql
    SELECT COUNT(c_pais)
    FROM   paises
    WHERE  cines > (
             SELECT AVG(cines)
             FROM   paises
           )
    #+end_src

69. Nombre de los clientes que no han pedido nada.
    #+begin_src sql
    SELECT nombre
    FROM   cliente
    WHERE  idcli NOT IN (
             SELECT idcli
             FROM   pedido
           )
    #+end_src

70. Cuantos pedidos se hicieron en 2017.
    #+begin_src sql
    SELECT COUNT(idped)
    FROM   pedido
    WHERE  fped like '__/__/17'
    #+end_src

71. Nombre de los clientes que no son ni de Madrid ni de Toledo.
    #+begin_src sql
    SELECT nombre
    FROM   cliente
    WHERE  ciudad != 'MADRID'
      AND  ciudad != 'TOLEDO'
    #+end_src

72. Descripcion de los articulos que se han vendido.
    #+begin_src sql
    SELECT descrip
    FROM   articulo
    WHERE  idart IN (
             SELECT idart
             FROM   detalle
           )
    #+end_src

73. Descripcion del articulo mas caro.
    #+begin_src sql
    SELECT descrip
    FROM   articulo
    WHERE  precio = (
             SELECT MAX(precio)
             FROM   articulo
           )
    #+end_src

74. Cuantos pedidos nos hacen entre madrileños y toledanos?
    #+begin_src sql
    SELECT COUNT(idped)
    FROM   pedido
    WHERE  idcli IN (
             SELECT idcli
             FROM   cliente
             WHERE  ciudad = 'MADRID'
                OR  ciudad = 'TOLEDO'
           )
    #+end_src

75. Cuantos pedidos se hacen en la segunda quincena del mes?
    #+begin_src sql
    SELECT COUNT(idped)
    FROM   pedido
    WHERE  SUBSTR(fped, 1, 2) > 15
    #+end_src

76. Listado de las ciudades con el numero de clientes que tenemos en
    cada provincia.
    #+begin_src sql
    SELECT   ciudad, COUNT(idcli)
    FROM     cliente
    GROUP BY ciudad
    #+end_src

77. Listado con los nombres de los clientes junto con el numero de
    pedidos que nos han hecho.
    #+begin_src sql
    SELECT   c.nombre, COUNT(p.idped)
    FROM     cliente c, pedido p
    WHERE    c.idcli = p.idcli
    GROUP BY c.nombre
    #+end_src

78. Que come Ana Kurnicova.
    #+begin_src sql
    SELECT descrip
    FROM   articulo
    WHERE  idart IN (
             SELECT idart
             FROM   detalle
             WHERE  idped IN (
                      SELECT idped
                      FROM   pedido
                      WHERE  idcli = (
                               SELECT idcli
                               FROM   cliente
                               WHERE  nombre = 'ANA KURNICOVA'
                             )
                    )
           )
    #+end_src

79. Listado de los articulos que vendemos junto con la cantidad que
    vendemos de ellos.
    #+begin_src sql
    SELECT   a.descrip, SUM(d.cantidad)
    FROM     articulo a, detalle d
    WHERE    a.idart = d.idart
    GROUP BY a.descrip
    ORDER BY a.descrip
    #+end_src

80. Que capital tenemos entre corderos y hamburguesas en el almacen?
    #+begin_src sql
    SELECT SUM(stock * precio)
    FROM   articulo
    WHERE  descrip IN (
             'CORDERO',
             'HAMBURGUESA'
           )
    #+end_src

81. Nombre de los clientes que no comen salchichas.
    #+begin_src sql
    SELECT nombre
    FROM   cliente
    WHERE  idcli NOT IN (
             SELECT idcli
             FROM   pedido
             WHERE  idped IN (
                      SELECT idped
                      FROM   detalle
                      WHERE  idart IN (
                               SELECT idart
                               FROM   articulo
                               WHERE  descrip = 'SALCHICHAS'
                             )
                    )
           )
    #+end_src

82. Cuantas paellas se comen en Toledo?
    #+begin_src sql
    SELECT SUM(cantidad)
    FROM   detalle
    WHERE  idped IN (
             SELECT idped
             FROM   pedido
             WHERE  idcli IN (
                      SELECT idcli
                      FROM   cliente
                      WHERE  ciudad = 'TOLEDO'
                    )
           )
      AND  idart = (
             SELECT idart
             FROM   articulo
             WHERE  descrip = 'PAELLA'
           )
    #+end_src

83. Listado con el idped junto con el importe del pedido.
    #+begin_src sql
    SELECT   d.idped, SUM(d.cantidad * a.precio)
    FROM     detalle d, articulo a
    WHERE    d.idart = a.idart
    GROUP BY d.idped
    #+end_src

84. Listado con las ciudades y el numero de clientes de cada ciudad.
    #+begin_src sql
    SELECT   ciudad, COUNT(idcli)
    FROM     cliente
    GROUP BY ciudad
    #+end_src

85. Nombre de las ciudades en las que tenemos mas de 2 clientes.
    #+begin_src sql
    SELECT   ciudad
    FROM     cliente
    GROUP BY ciudad
    HAVING   COUNT(idcli) > 2
    #+end_src

86. En que formatos tenemos mas de 10 peliculas?
    #+begin_src sql
    SELECT   formato
    FROM     peliculas
    GROUP BY formato
    HAVING   COUNT(c_peli) > 10
    #+end_src

87. Titulo de las peliculas que hemos alquilado mas de una vez.
    #+begin_src sql
    SELECT   titulo
    FROM     peliculas
    WHERE    c_peli IN (
               SELECT   c_peli
               FROM     alquiler
               GROUP BY c_peli
               HAVING   COUNT(c_socio) > 1
             )
    #+end_src

88. Que paises producen menos de 3 peliculas?
    #+begin_src sql
    SELECT   pa.nombre_pais
    FROM     peliculas pe, paises pa
    WHERE    pe.c_pais = pa.c_pais
    GROUP BY pa.nombre_pais
    HAVING   COUNT(pe.c_peli) < 3
    #+end_src

89. Nombre de los socios que han alquilado mas de 2 peliculas.
    #+begin_src sql
    SELECT   s.nombre
    FROM     socios s, alquiler a
    WHERE    s.c_socio = a.c_socio
    GROUP BY s.nombre
    HAVING   COUNT(a.c_peli) > 2
    #+end_src

90. Poner a oferta todas las peliculas anteriores a 2010.
    #+begin_src sql
    UPDATE peliculas
    SET    oferta = 'S'
    WHERE  anno < 2010
    #+end_src

91. Rebajar el PRECIO de todas las peliculas un 25%.
    #+begin_src sql
    UPDATE peliculas
    SET    precio = precio - precio * 25/100
    #+end_src

92. Dia sin IVA. Quitar el IVA a todas las peliculas.
    #+begin_src sql
    UPDATE peliculas
    SET    precio = precio / 121 * 100
    #+end_src

93. Poner a 1 euro todas las peliculas españolas.
    #+begin_src sql
    UPDATE peliculas
    SET    precio = 1
    WHERE  c_pais IN (
             SELECT c_pais
             FROM   paises
             WHERE  nombre_pais LIKE 'España'
           )
    #+end_src

94. Listado con los nombres de socios junto con el titulo de la
    pelicula mal alquilada.
    #+begin_src sql
    SELECT s.nombre, p.titulo
    FROM   socios s, peliculas p, alquiler a
    WHERE  s.c_socio = a.c_socio
      AND  a.c_peli = p.c_peli
      AND  a.total != a.ndias * p.precio
    #+end_src

95. Listado con los alquileres con el precio cobrado junto con el
    precio que se deberia haber cobrado.
    #+begin_src sql
    SELECT p.titulo, a.total "Cobrado", a.ndias * p.precio "Precio correcto"
    FROM   peliculas p, alquiler a
    WHERE  a.c_peli = p.c_peli
      AND  a.total != a.ndias * p.precio
    #+end_src

96. Actualizar bien la base de datos y poner el valor correcto de
    TOTAL.
    #+begin_src sql
    UPDATE alquiler a
    SET    total = ndias * (
             SELECT precio
             FROM   peliculas p
             WHERE  p.c_peli = a.c_peli
           )
    #+end_src

97. Listado con todos los nombres de los socios junto con el total que
    se han gastado en el videoclub.
    #+begin_src sql
    SELECT nombre, (
             SELECT NVL(SUM(total), 0)
             FROM alquiler a
             WHERE a.c_socio = s.c_socio
           ) "Total gastado"
    FROM   socios s
    #+end_src

98. Cual es el pais que mas peliculas ha producido.
    #+begin_src sql
    SELECT nombre_pais
    FROM   paises
    WHERE  c_pais = (
             SELECT   c_pais
             FROM     peliculas
             GROUP BY c_pais
             HAVING   COUNT(c_pais) = (
                        SELECT MAX(count)
                        FROM (
                         SELECT   COUNT(c_pais) count
                         FROM     peliculas
                         GROUP BY c_pais
                       )
                     )
           )
    #+end_src

99. Quitar 100 cines a los paises que no alquilan sus peliculas.
    #+begin_src sql
    UPDATE paises p
    SET    cines = cines - 100
    WHERE  c_pais NOT IN (
             SELECT c_pais
             FROM   peliculas
             WHERE  c_peli IN (
                      SELECT c_peli
                      FROM   alquiler
                    )
           )
    #+end_src

100. En que formato tenemos mas peliculas.
     #+begin_src sql
     SELECT   formato
     FROM     peliculas
     GROUP BY formato
     HAVING   COUNT(formato) = (
                SELECT MAX(count)
                FROM (
                  SELECT   COUNT(formato) count
                  FROM     peliculas
                  GROUP BY formato
                )
              )
     #+end_src

101. Poner en oferta solo aquellas peliculas que no se alquilen.
     #+begin_src sql
     UPDATE peliculas
     SET    oferta = 'S'
     WHERE  c_peli NOT IN (
              SELECT c_peli
              FROM   alquiler
            )
     #+end_src

102. Escribir correctamente los nombres de los socios.
     #+begin_src sql
     UPDATE socios
     SET    nombre = INITCAP(nombre),
            ape1 = INITCAP(ape1),
            ape2 = INITCAP(ape2)
     #+end_src

103. Añadir a la tabla socios el atributo GASTADO (numerico de 6):
     #+begin_src sql
     ALTER TABLE socios
     ADD   gastado NUMBER(6)
     #+end_src

104. Poner el campo GASTADO con el valor correcto con el total gastado
     de cada socio.
     #+begin_src sql
     UPDATE socios s
     SET    gastado = (
              SELECT NVL(SUM(ndias * (
                       SELECT precio
                       FROM   peliculas p
                       WHERE  p.c_peli = a.c_peli
                     )), 0)
              FROM   alquiler a
              WHERE  a.c_socio = s.c_socio
            )
     #+end_src

105. Cual es el valor en euros de todo lo que tenemos en stock?
     #+begin_src sql
     SELECT SUM(precio * stock)
     FROM   articulo
     #+end_src

106. Bajar un 25% el precio de los articulos que se venden.
     #+begin_src sql
     UPDATE articulo a
     SET    precio = precio * 0.75
     WHERE  idart IN (
              SELECT idart
              FROM   detalle
            )
     #+end_src

107. Que articulos se piden mas de una vez en el mismo pedido.
     #+begin_src sql
     SELECT descrip
     FROM   articulo
     WHERE  idart IN (
              SELECT idart
              FROM   detalle
              WHERE  cantidad > 1
            )
     #+end_src

108. Cual fue la ultima vez que se vendio CORDERO.
     #+begin_src sql
     SELECT MAX(fped)
     FROM   pedido
     WHERE idped IN (
             SELECT idped
             FROM   detalle
             WHERE  idart = (
                      SELECT idart
                      FROM   articulo
                      WHERE  descrip = 'CORDERO'
                    )
           )
     #+end_src

109. Que codigos de pedido incluyen mas de 2 articulos diferentes.
     #+begin_src sql
     SELECT   idped
     FROM     detalle
     GROUP BY idped
     HAVING   COUNT(idart) > 2
     #+end_src

110. Nombre de los clientes que pagan despues de 10 dias de haber
     hecho el pedido.
     #+begin_src sql
     SELECT nombre
     FROM   cliente
     WHERE  idcli IN (
              SELECT idcli
              FROM   pedido
              WHERE  ffac - fped > 10
            )
     #+end_src

111. Cuantos clientes se llaman MARIA de nombre?
     #+begin_src sql
     SELECT COUNT(idcli)
     FROM   cliente
     WHERE  nombre like 'MARIA%'
     #+end_src

112. Quien hizo el pedido con mas articulos.
     #+begin_src sql
     SELECT nombre
     FROM   cliente
     WHERE  idcli = (
              SELECT idcli
              FROM   pedido
              WHERE  idped = (
                       SELECT   idped
                       FROM     detalle
                       GROUP BY idped
                       HAVING   SUM(cantidad) = (
                                  SELECT   MAX(SUM(cantidad))
                                  FROM     detalle
                                  GROUP BY idped
                                )
                     )
            )
     #+end_src

113. Nombre del cliente que pidio mas PAELLAS.
     #+begin_src sql
     SELECT nombre
     FROM   cliente
     WHERE  idcli IN (
              SELECT   idcli
              FROM     pedido p, detalle d
              WHERE    p.idped = d.idped
                AND    d.idart = (
                         SELECT idart
                         FROM   articulo
                         WHERE  descrip = 'HAMBURGUESA'
                       )
              GROUP BY idcli
              HAVING   SUM(d.cantidad) > 2
            )
     #+end_src

114. Nombre de los clientes que no han probado las ALBONDIGAS.
     #+begin_src sql
     SELECT nombre
     FROM   cliente
     WHERE  idcli NOT IN (
              SELECT idcli
              FROM   pedido
              WHERE  idped IN (
                       SELECT idped
                       FROM   detalle
                       WHERE  idart = (
                                SELECT idart
                                FROM   articulo
                                WHERE  descrip = 'ALBONDIGAS'
                              )
                     )
            )
     #+end_src

115. Quien ha comido mas de dos HAMBURGUESAS.
     #+begin_src sql
     SELECT nombre
     FROM   cliente
     WHERE  idcli IN (
              SELECT idcli
              FROM   pedido
              WHERE  idped IN (
                       SELECT   idped
                       FROM     detalle
                       WHERE    idart = (
                                  SELECT idart
                                  FROM   articulo
                                  WHERE  descrip = 'HAMBURGUESA'
                                )
                       GROUP BY idped
                       HAVING   SUM(cantidad) > 2
                     )
            )
     #+end_src

116. Cuantos clientes han hecho menos de 2 pedidos.
     #+begin_src sql
     SELECT COUNT(idcli)
     FROM   cliente
     WHERE  idcli NOT IN (
              SELECT   idcli
              FROM     pedido
              GROUP BY idcli
              HAVING   COUNT(idped) >= 2
            )
     #+end_src

117. Suponiendo que cuando abrimos la empresa teniamos 100 unidades de
     cada articulo. Poner correctamente el valor de STOCK.
     #+begin_src sql
     UPDATE articulo a
     SET    stock = 100 - (
              SELECT NVL(SUM(cantidad), 0)
              FROM   detalle
              WHERE  idart = a.idart
            )
     #+end_src

118. Añadir el campo GASTADO a la tabla cliente y ponerlo con el valor
     correcto.
     #+begin_src sql
     ALTER TABLE cliente
     ADD   gastado NUMBER(6)
     #+end_src

     #+begin_src sql
     UPDATE cliente c
     SET    gastado = (
              SELECT   NVL(SUM(d.cantidad * (
                         SELECT precio
                         FROM   articulo
                         WHERE  idart = d.idart
                       )), 0)
              FROM     pedido p, detalle d
              WHERE    p.idcli = c.idcli
                AND    p.idped = d.idped
            )
     #+end_src
